"""
Config paketi
"""
from .settings import (
    KANVAS_GENISLIK,
    KANVAS_YUKSEKLIK,
    INITIAL_DELAY,
    SPEED_UP_DECREMENT,
    MIN_DELAY,
    SELECTION_COLOR_ACTIVE,
    TOP_KONFIGURASYONLARI,
    KONTROL_KONFIGURASYONLARI
)

__all__ = [
    'KANVAS_GENISLIK',
    'KANVAS_YUKSEKLIK',
    'INITIAL_DELAY',
    'SPEED_UP_DECREMENT',
    'MIN_DELAY',
    'SELECTION_COLOR_ACTIVE',
    'TOP_KONFIGURASYONLARI',
    'KONTROL_KONFIGURASYONLARI'
]